/*HEADER*/
export const CHANGE_DARKMODE = 'CHANGE_DARKMODE'

/*BANNER*/
export const NEXT_BANNER = 'NEXT_BANNER'
export const PREV_BANNER = 'PREV_BANNER'

/*PRODUCTSBLOCK*/
export const PREV_TOP_PRODUCT = 'PREV_TOP_PRODUCT'
export const NEXT_TOP_PRODUCT = 'NEXT_TOP_PRODUCT'
export const PREV_NEW_PRODUCT = 'PREV_NEW_PRODUCT'
export const NEXT_NEW_PRODUCT = 'NEXT_NEW_PRODUCT'
export const INITIAL_NEW_PRODUCTS = 'INITIAL_NEW_PRODUCTS'
export const INITIAL_TOP_PRODUCTS = 'INITIAL_TOP_PRODUCTS'