/*HEADER*/
export const CHANGE_DARKMODE = 'CHANGE_DARKMODE';

/*BANNER*/
export const NEXT_BANNER = 'NEXT_BANNER';
export const PREV_BANNER = 'PREV_BANNER';

/*PRODUCTSBLOCK*/
export const PREV_TOP_PRODUCT = 'PREV_TOP_PRODUCT';
export const NEXT_TOP_PRODUCT = 'NEXT_TOP_PRODUCT';
export const PREV_NEW_PRODUCT = 'PREV_NEW_PRODUCT';
export const NEXT_NEW_PRODUCT = 'NEXT_NEW_PRODUCT';
export const INITIAL_NEW_PRODUCTS = 'INITIAL_NEW_PRODUCTS';
export const INITIAL_TOP_PRODUCTS = 'INITIAL_TOP_PRODUCTS';

/*CATALOG*/
export const SET_FILTER = 'SET_FILTER';
export const SET_CATALOG = 'SET_CATALOG';
export const SHOW_MORE_PRODUCTS = 'SHOW_MORE_PRODUCTS';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const SET_SHOW_SEARCH = 'SET_SHOW_SEARCH';

/*CART*/
export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_PRODUCT_COUNT = 'CHANGE_PRODUCT_COUNT';
export const SET_SHOW_CART = 'SET_SHOW_CART';
export const BUY_CART = 'BUY_CART';
