/*HEADER*/
export const CHANGE_DARKMODE = 'CHANGE_DARKMODE'

/*BANNER*/

/*PRODUCTSBLOCK*/
export const PREV_TOP_PRODUCT = 'PREV_TOP_PRODUCT'
export const NEXT_TOP_PRODUCT = 'NEXT_TOP_PRODUCT'
export const PREV_NEW_PRODUCT = 'PREV_NEW_PRODUCT'
export const NEXT_NEW_PRODUCT = 'NEXT_NEW_PRODUCT'